'use client'
import { appWithTranslation } from 'next-i18next'
import '@/styles/globals.css'
import Navigation from '@/components/Navigation/Navigation'
import Footer from '@/components/Footer/Footer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>My Portfolio</title>
      </head>
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}

export default appWithTranslation(RootLayout)
